"""
AEGIS GitHub PR Creator
Automatically creates hotfix pull requests with AI-generated explanation and context.
Supports both real GitHub API and simulation mode for demo.
"""
import os
from loguru import logger
from src.models import HealResult, RCAResult


class PRCreator:
    """
    Creates GitHub pull requests for code/config fixes generated by AEGIS.
    In simulation mode, logs what the PR would contain.
    In production mode, uses PyGithub to create real PRs.
    """

    def __init__(self):
        self.token = os.environ.get("GITHUB_TOKEN")
        self.repo_owner = os.environ.get("GITHUB_REPO_OWNER")
        self.repo_name = os.environ.get("GITHUB_REPO_NAME")
        self.simulation = not all([self.token, self.repo_owner, self.repo_name])
        if self.simulation:
            logger.info("[PR] Simulation mode — PRs will be logged, not created")

    async def create(self, rca: RCAResult, heal: HealResult) -> str:
        """Returns PR URL (real or simulated)."""
        if not heal.has_code_fix or not heal.fix_files:
            return ""

        branch_name = f"aegis-hotfix/{rca.failure_type.value}/{heal.incident_id.lower()}"
        pr_title = f"[AEGIS Auto-Fix] {rca.root_cause[:80]}"
        pr_body = self._build_pr_body(rca, heal)

        if self.simulation:
            return self._simulate_pr(branch_name, pr_title, pr_body, heal)

        return await self._create_real_pr(branch_name, pr_title, pr_body, heal)

    def _build_pr_body(self, rca: RCAResult, heal: HealResult) -> str:
        files_list = "\n".join([f"- `{f['path']}`: {f['description']}" for f in heal.fix_files])
        return f"""## 🛡️ AEGIS Autonomous Hotfix

**Incident:** `{heal.incident_id}`  
**Root Cause:** {rca.root_cause}  
**Confidence:** {rca.confidence:.0f}%  
**Risk Level:** {rca.risk_level.value.upper()}  

---

### What Happened
{rca.explanation}

### What This Fix Does
{heal.action_taken}

### Files Changed
{files_list}

### Outcome After Fix
{heal.outcome}

### Prevention
> Add schema contract tests to CI pipeline to catch upstream changes before they reach production.

---
*This PR was automatically generated by AEGIS. Review and merge if the fix looks correct.*  
*For high-risk changes, manual verification is required before merging.*
"""

    def _simulate_pr(self, branch: str, title: str, body: str, heal: HealResult) -> str:
        logger.info(f"[PR] Simulated PR created:")
        logger.info(f"  Branch: {branch}")
        logger.info(f"  Title:  {title}")
        for f in heal.fix_files:
            logger.info(f"  File:   {f['path']}")
        fake_pr_num = abs(hash(heal.incident_id)) % 9000 + 1000
        url = f"https://github.com/{self.repo_owner or 'your-org'}/{self.repo_name or 'your-repo'}/pull/{fake_pr_num}"
        logger.success(f"[PR] Simulated URL: {url}")
        return url

    async def _create_real_pr(self, branch: str, title: str, body: str, heal: HealResult) -> str:
        try:
            from github import Github, GithubException
            g = Github(self.token)
            repo = g.get_repo(f"{self.repo_owner}/{self.repo_name}")
            default_branch = repo.default_branch
            base_sha = repo.get_branch(default_branch).commit.sha
            repo.create_git_ref(ref=f"refs/heads/{branch}", sha=base_sha)

            for fix_file in heal.fix_files:
                repo.create_file(
                    path=fix_file["path"],
                    message=f"[AEGIS] Auto-fix: {fix_file['description']}",
                    content=fix_file["content"],
                    branch=branch,
                )

            pr = repo.create_pull(
                title=title,
                body=body,
                head=branch,
                base=default_branch,
            )
            try:
                pr.add_to_labels("aegis-auto-fix", "reliability")
            except Exception:
                pass  # Labels may not exist — non-fatal
            logger.success(f"[PR] Created: {pr.html_url}")
            return pr.html_url
        except Exception as e:
            logger.warning(f"[PR] Real PR failed ({type(e).__name__}) — using simulation. "
                           f"Tip: regenerate GitHub token with 'repo' (full write) scope.")
            return self._simulate_pr(branch, title, body, heal)
